version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: phonecase_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: m1wy5RXNIkS8U1YUTjWGDioFuooqrbnn
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: